#############################################################################
# Makefile for building: game_rexxu
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue May 7 22:16:13 2013
# Project:  game_rexxu.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile game_rexxu.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bonus.cpp \
		coffee.cpp \
		dictionary.cpp \
		game.cpp \
		graphicwindow.cpp \
		grid.cpp \
		ladebug.cpp \
		main.cpp \
		point_down.cpp \
		point_left.cpp \
		point_right.cpp \
		point_up.cpp \
		ram.cpp \
		redekopp.cpp \
		tree.cpp moc_main.cpp
OBJECTS       = bonus.o \
		coffee.o \
		dictionary.o \
		game.o \
		graphicwindow.o \
		grid.o \
		ladebug.o \
		main.o \
		point_down.o \
		point_left.o \
		point_right.o \
		point_up.o \
		ram.o \
		redekopp.o \
		tree.o \
		moc_main.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		game_rexxu.pro
QMAKE_TARGET  = game_rexxu
DESTDIR       = 
TARGET        = game_rexxu

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: game_rexxu.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile game_rexxu.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile game_rexxu.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/game_rexxu1.0.0 || $(MKDIR) .tmp/game_rexxu1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/game_rexxu1.0.0/ && $(COPY_FILE) --parents bonus.h coffee.h dictionary.h graphicwindow.h grid.h ladebug.h main.h point_down.h point_left.h point_right.h point_up.h ram.h redekopp.h thing.h tree.h .tmp/game_rexxu1.0.0/ && $(COPY_FILE) --parents bonus.cpp coffee.cpp dictionary.cpp game.cpp graphicwindow.cpp grid.cpp ladebug.cpp main.cpp point_down.cpp point_left.cpp point_right.cpp point_up.cpp ram.cpp redekopp.cpp tree.cpp .tmp/game_rexxu1.0.0/ && (cd `dirname .tmp/game_rexxu1.0.0` && $(TAR) game_rexxu1.0.0.tar game_rexxu1.0.0 && $(COMPRESS) game_rexxu1.0.0.tar) && $(MOVE) `dirname .tmp/game_rexxu1.0.0`/game_rexxu1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/game_rexxu1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp
moc_main.cpp: grid.h \
		thing.h \
		redekopp.h \
		graphicwindow.h \
		point_up.h \
		point_down.h \
		point_left.h \
		point_right.h \
		ladebug.h \
		bonus.h \
		tree.h \
		ram.h \
		dictionary.h \
		coffee.h \
		main.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) main.h -o moc_main.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bonus.o: bonus.cpp bonus.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bonus.o bonus.cpp

coffee.o: coffee.cpp coffee.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coffee.o coffee.cpp

dictionary.o: dictionary.cpp dictionary.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dictionary.o dictionary.cpp

game.o: game.cpp main.h \
		grid.h \
		thing.h \
		redekopp.h \
		graphicwindow.h \
		point_up.h \
		point_down.h \
		point_left.h \
		point_right.h \
		ladebug.h \
		bonus.h \
		tree.h \
		ram.h \
		dictionary.h \
		coffee.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

graphicwindow.o: graphicwindow.cpp graphicwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicwindow.o graphicwindow.cpp

grid.o: grid.cpp grid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o grid.cpp

ladebug.o: ladebug.cpp ladebug.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ladebug.o ladebug.cpp

main.o: main.cpp main.h \
		grid.h \
		thing.h \
		redekopp.h \
		graphicwindow.h \
		point_up.h \
		point_down.h \
		point_left.h \
		point_right.h \
		ladebug.h \
		bonus.h \
		tree.h \
		ram.h \
		dictionary.h \
		coffee.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

point_down.o: point_down.cpp point_down.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point_down.o point_down.cpp

point_left.o: point_left.cpp point_left.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point_left.o point_left.cpp

point_right.o: point_right.cpp point_right.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point_right.o point_right.cpp

point_up.o: point_up.cpp point_up.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point_up.o point_up.cpp

ram.o: ram.cpp ram.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ram.o ram.cpp

redekopp.o: redekopp.cpp redekopp.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o redekopp.o redekopp.cpp

tree.o: tree.cpp tree.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tree.o tree.cpp

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

